### Register

POST http://localhost:9999/auth/new
Accept: application/json
Content-Type: application/json

{
  "email": "davidk@outlook.com",
  "firstName": "David",
  "lastName": "Kröll",
  "password": "asdf1234"
}

### Get auth token

POST http://localhost:9999/auth
Accept: application/json
Content-Type: application/json

{
  "email": "davidk@outlook.com",
  "password": "asdf1234"
}

### Get auth token
### should fail

POST http://localhost:9999/auth
Accept: application/json
Content-Type: application/json

{
  "email": "hmersh41@dell.com",
  "password": "wrong password"
}

### Get all shortcuts from authenticated user

GET http://localhost:9999/api/shortcuts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

### Get all shortcuts from unauthenticated user
### should fail

GET http://localhost:9999/api/shortcuts
Accept: application/json

### Get all shortcuts with invalid jwt
### should fail

GET http://localhost:9999/api/shortcuts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

### Get shortcut with given ID

GET http://localhost:9999/api/shortcuts/200
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

### Get shortcut not belonging to user
### should fail

GET http://localhost:9999/api/shortcuts/7
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjAwMzY2ZmI5LWNkNzYtNDdlMC1iM2M2LWNiZDYxMTY1MGQ5ZSIsImV4cCI6MTU1Mjk4MDgxMn0.ZigpbO2X26HSlWAZ-XnWLJTy8eYArDo0i8CIZlPal5Y

### Create shortcut without authorization
### should fail

POST http://localhost:9999/api/shortcuts
Content-Type: application/json
Accept: application/json

{
  "shortIdentifier": "htl2",
  "redirectURL": "http://htl-villach.at",
  "redirectStatus": 301,
  "validThru": "2019-04-01T08:00:00.000+01:00"
}

### Create shortcut with authorization

POST http://localhost:9999/api/shortcuts
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

{
  "shortIdentifier": "htl-viladsfb",
  "redirectURL": "http://htl-villach.at",
  "redirectStatus": 301,
  "validThru": "2019-04-01T08:00:00.000+01:00"
}

### Update shortcut

PUT http://localhost:9999/api/shortcuts/7
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

{
  "shortIdentifier": "h",
  "redirectURL": "http://htl-villach.at",
  "redirectStatus": 302,
  "validThru": "2027-04-01T08:00:00.000+01:00"
}

### Update shortcut not belonging to user
### should fail

PUT http://localhost:9999/api/shortcuts/7
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

{
  "shortIdentifier": "htl34",
  "redirectURL": "http://htl-villach.at",
  "redirectStatus": 302,
  "validThru": "2027-04-01T08:00:00.000+01:00"
}

### Delete shortcut not belonging to user
### should fial

DELETE http://localhost:9999/api/shortcuts/7
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

### Delete shortcut

DELETE http://localhost:9999/api/shortcuts/200
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6IjExIiwiZXhwIjoxNTU0Mzc2MzA4fQ.fvwF84sEIdqtWYuuXysGZXBQrKU2xn3UTUsxXYsLIds

###

